chore: add comment for OP_DEREFSET

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,18 +1,18 @@
 #!/bin/sh
 
+# Run clang-format
+clang-format src/*.c src/*.h --dry-run -Werror
+if [ $? -ne 0 ]; then
+  echo "Error: Code should be formatted with clang-format."
+  exit 1
+fi
+
 # Run tests
 make clean
 make -j$(nproc) debug=vm
 make test
 if [ $? -ne 0 ]; then
   echo "Tests failed."
-  exit 1
-fi
-
-# Run clang-format
-clang-format src/*.c src/*.h --dry-run
-if [ $? -ne 0 ]; then
-  echo "Error: Code should be formatted with clang-format."
   exit 1
 fi
 
